### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by MelodieAnge** [Wildric-Auric/MidJourney-Wrapper#30] opened 2023-03-01 23:23 UTC
Hiii , i'm trying your bot but when i try to generate image , i got this error {"message": "Unknown Integration", "code": 10005}
400 , if you can help me it would be really nice .

Thank you .

**Comment by Wildric-Auric** [comment] 2023-03-02 00:18
It's a duplicate of issue #15; 
you should have the official midjourney [bot](https://docs.midjourney.com/docs/invite-the-bot) in the same server, like said in the readme.

**Comment by MelodieAnge** [comment] 2023-03-02 01:21
thank you

**Closed** 2023-03-02 10:18 UTC
